### ISSUE TITLE
Ctrl + ; seems broken for me

### ISSUE THREAD

**Issue by 404salad** [Anderbone/leetcode-shortcut-browser-extension#4]
every time i press ctrl + ; this error shows up 
![image](https://github.com/Anderbone/leetcode-shortcut-browser-extension/assets/110289934/bc63f0af-0ce8-453d-9c31-d9063a0446a7)

**Comment by 404salad** [comment]
Its likely because they changed the button name

**Comment by Anderbone** [comment]
Yes, they changed the button name. Now as ctrl + ' is officially supported, updated this shortcut using ctrl + '
